spring.application.name=rideshare
server.port=8081

spring.data.mongodb.uri=mongodb+srv://USERNAME:PASSWORD@cluster0.xxauxdl.mongodb.net/rideshare?retryWrites=true&w=majority

jwt.secret=sdfghjasdsdtryukj
jwt.expiration-ms=3600000
