spring.application.name=rideshare
server.port=8081

spring.data.mongodb.uri=mongodb+srv://RideUser:Mr%23bond0025@cluster0.xxauxdl.mongodb.net/rideshare?retryWrites=true&w=majority
jwt.secret=YXN1cGVyLXNlY3JldC1leGFtcGxlLXN1cGVyLXNlY3JldC1leGFtcGxl
jwt.expiration-ms=3600000
